
name: build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ github.ref_name }} OS:${{ matrix.os }} GHC:${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-15]
        ghc:
          - "9.6"
          - "9.12"
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
      - name: build
        run: |
          mkdir dist
          cabal install exe:werge --install-method=copy --overwrite-policy=always --installdir=dist
          strip dist/werge
          mv dist/werge dist/werge-${{ github.ref_name }}_${{ matrix.os }}_ghc-${{ matrix.ghc }}
          xz dist/werge-*
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/werge-*.xz
